name: Pervaziv AI Code Review

on:
  push:
    branches:
      - main        # triggers on merge to main
  
jobs:
  cortex-review:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: write
      pull-requests: write
      checks: write 
    steps:
      - uses: jyothsnalade/cortex-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          console-url: https://console.pervaziv.com
          
          
